NEXT_PUBLIC_SUPABASE_URL=https://nqtoaqhgusjqmrdlkzyl.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_xtW2RmTiv8dLoFpb3zmMfw_7DrxjaCq
SUPABASE_SERVICE_KEY=sb_secret_3QJZ88R21M4pHCbC0McooQ_ANWIvGvl
